// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of the `get_app_info` IPC command — the smoke-test round-trip that
 * proves Rust → Tauri → React wiring and the ts-rs binding pipeline.
 */
export type AppInfo = { 
/**
 * Product name.
 */
name: string, 
/**
 * `hive-core` crate version.
 */
core_version: string, 
/**
 * Backend build profile (`debug` / `release`).
 */
build_profile: string, };
