// Parity tests for the derived token layer.
//
// The claim this file has to defend is narrow and specific: *no shipped Windows
// colour moved*. `applyTheme()` now computes the OKLCH-derived tokens in JS
// instead of leaving `oklch(from …)` to the engine, and the whole point of
// doing that was to make macOS agree with Windows — not to restyle Windows.
//
// So the expected values are not hand-written and not generated by the code
// under test. They were measured out of real rendered Chromium pixels, which is
// the only instrument that answers the actual question: computed style
// serialises an out-of-gamut `oklch()` straight back as `oklch()`, telling you
// what you asked for rather than what the user saw. The fixture is shared with
// the mobile companion (`mobile-companion/app/src/theme/__tests__/fixtures/`),
// regenerated there by `bun run tools/extract-desktop-tokens.ts`.
//
// If a value here changes, the desktop's appearance changed. That should be a
// deliberate design call, not a side effect.

import { describe, expect, it, beforeEach } from "vitest";
import { THEMES, deriveTokens, applyTheme, turnAccentColors, CHAT } from "./theme";
import { formatColor, mixSrgb, oklchReplaceL } from "./color";
import fixture from "./__fixtures__/derived-tokens.json";

const measured = (fixture as { tokens: Record<string, string> }).tokens;

// The stylesheet as text, for the guards at the bottom.
//
// Not `import "@/styles.css?raw"`: vitest stubs CSS imports (`test.css` is off)
// and `?raw` is stubbed along with them, so that arrives as an empty string and
// every guard below would pass vacuously. Reading the file is the honest way,
// and the specifier is assembled rather than written literally so TypeScript
// does not try to resolve it — the web app has no `@types/node`, and adding the
// package to type one `readFileSync` in one test is a poor trade.
const { readFileSync } = (await import(/* @vite-ignore */ "node:" + "fs")) as {
  readFileSync: (path: string, encoding: string) => string;
};
// vitest runs from the project root; `import.meta.url` under jsdom is not a
// usable file: URL. If this ever resolves wrong the read throws, which is the
// failure mode we want — a guard that cannot find its input must not pass.
const root = (globalThis as unknown as { process: { cwd(): string } }).process.cwd();
const styleSheet = readFileSync(`${root}/src/styles.css`, "utf8");

const THEME_NAMES = Object.keys(THEMES) as (keyof typeof THEMES)[];
const SCHEMES = ["light", "dark"] as const;

/// The fixture keys the *desktop* is responsible for: everything the stylesheet
/// used to build with `oklch()`. The `color-mix()` tokens in the same fixture
/// are still evaluated by CSS here (engines agree on those) and are exercised
/// by the mobile suite instead.
const OKLCH_TOKENS = [
  "successInk",
  "dangerInk",
  "warnInk",
  "warmInk",
  "accentFill",
  "warmFill",
] as const;

/// Fixture spells the turn identities by role; the theme spells them by accent.
const IDENTITIES = [
  { fixture: "human", identity: "warm" },
  { fixture: "agent", identity: "cool" },
  { fixture: "shared", identity: "muted" },
] as const;

describe("derived tokens match rendered Chromium pixels", () => {
  for (const name of THEME_NAMES) {
    for (const scheme of SCHEMES) {
      it(`${name}.${scheme}`, () => {
        const d = deriveTokens(THEMES[name][scheme]);
        for (const token of OKLCH_TOKENS) {
          expect(`${name}.${scheme}.${token}: ${d[token]}`).toBe(
            `${name}.${scheme}.${token}: ${measured[`${name}.${scheme}.${token}`]}`,
          );
        }
        for (const { fixture, identity } of IDENTITIES) {
          expect(`${name}.${scheme}.${fixture}.rail: ${d.rail[identity]}`).toBe(
            `${name}.${scheme}.${fixture}.rail: ${measured[`${name}.${scheme}.${fixture}.rail`]}`,
          );
          // The fixture calls the tinted author name "tag" (it is --tn, used by
          // both .tt-handle and .tt-tag.live).
          expect(`${name}.${scheme}.${fixture}.tag: ${d.name[identity]}`).toBe(
            `${name}.${scheme}.${fixture}.tag: ${measured[`${name}.${scheme}.${fixture}.tag`]}`,
          );
        }
      });
    }
  }

  it("covers every theme the shell ships", () => {
    // Guards against a new palette landing without a regenerated fixture — the
    // loop above would silently pass by comparing undefined to undefined if a
    // key were missing, so assert the fixture is populated for each one.
    for (const name of THEME_NAMES) {
      for (const scheme of SCHEMES) {
        expect(measured[`${name}.${scheme}.dangerInk`], `${name}.${scheme} missing`).toMatch(
          /^rgb\(/,
        );
      }
    }
  });
});

describe("the muted accent chain stays unrounded", () => {
  // --hive-accent-muted is a color-mix that CSS still evaluates, but the muted
  // turn rail derives from it in OKLCH. The browser kept full precision through
  // the mix; rounding to 8-bit in between costs a count or two.
  it("matches the browser's color-mix", () => {
    for (const name of THEME_NAMES) {
      for (const scheme of SCHEMES) {
        const p = THEMES[name][scheme];
        expect(formatColor(mixSrgb(p.ink, 34, p.panel))).toBe(
          measured[`${name}.${scheme}.accentMuted`],
        );
      }
    }
  });

  it("rounding the intermediate would actually change a rail", () => {
    // If this ever stops being true the precision note above is dead weight and
    // should be deleted rather than left as folklore.
    const differs = THEME_NAMES.flatMap((name) =>
      SCHEMES.map((scheme) => {
        const p = THEMES[name][scheme];
        const exact = mixSrgb(p.ink, 34, p.panel);
        const rounded = {
          r: Math.round(exact.r),
          g: Math.round(exact.g),
          b: Math.round(exact.b),
          a: exact.a,
        };
        const l = CHAT[scheme].turnNameL;
        return formatColor(oklchReplaceL(exact, l)) !== formatColor(oklchReplaceL(rounded, l));
      }),
    );
    expect(differs).toContain(true);
  });
});

describe("the platform split this closed", () => {
  it("clip and the CSS Color 4 algorithm disagree visibly on dark dangerInk", () => {
    const danger = "rgb(240,112,112)";
    const l = CHAT.dark.accentInkL;
    // Chromium (what we ship) vs WebKit (what macOS rendered before this).
    expect(formatColor(oklchReplaceL(danger, l, "clip"))).toBe("rgb(255, 157, 155)");
    expect(formatColor(oklchReplaceL(danger, l, "css4"))).toBe("rgb(255, 173, 170)");
  });

  it("defaults to the Chromium behaviour", () => {
    const danger = "rgb(240,112,112)";
    const l = CHAT.dark.accentInkL;
    expect(formatColor(oklchReplaceL(danger, l))).toBe(
      formatColor(oklchReplaceL(danger, l, "clip")),
    );
    expect(deriveTokens(THEMES.pollen.dark).dangerInk).toBe("rgb(255, 157, 155)");
  });
});

describe("per-turn accents (personal agents)", () => {
  it("derives a rail and name from an arbitrary avatar colour", () => {
    // A personal agent's accent is a stored hex, not one of the three theme
    // identities, so it cannot be precomputed by applyTheme().
    const { rail, name } = turnAccentColors("#d8961f", "light");
    expect(rail).toMatch(/^rgb\(/);
    expect(name).toMatch(/^rgb\(/);
    expect(rail).not.toBe(name);
  });

  it("agrees with the theme identity when handed the theme's own accent", () => {
    const p = THEMES.harbor.dark;
    const d = deriveTokens(p);
    expect(turnAccentColors(p.accentCool, "dark")).toEqual({ rail: d.rail.cool, name: d.name.cool });
  });

  it("re-derives per scheme", () => {
    expect(turnAccentColors("#d8961f", "light")).not.toEqual(turnAccentColors("#d8961f", "dark"));
  });

  it("leaves an unparseable accent alone rather than blanking the rail", () => {
    expect(turnAccentColors("var(--nope)", "light")).toEqual({
      rail: "var(--nope)",
      name: "var(--nope)",
    });
  });
});

describe("applyTheme publishes resolved colours, not lightness knobs", () => {
  beforeEach(() => {
    document.documentElement.removeAttribute("style");
  });

  it("sets every derived token as a finished rgb()", () => {
    const p = THEMES.pollen.dark;
    applyTheme(p);
    const d = deriveTokens(p);
    const css = (n: string) => document.documentElement.style.getPropertyValue(n);
    expect(css("--hive-danger-ink")).toBe(d.dangerInk);
    expect(css("--hive-success-ink")).toBe(d.successInk);
    expect(css("--hive-warn-ink")).toBe(d.warnInk);
    expect(css("--hive-warm-ink")).toBe(d.warmInk);
    expect(css("--hive-accent-fill")).toBe(d.accentFill);
    expect(css("--hive-warm-fill")).toBe(d.warmFill);
    for (const { identity } of IDENTITIES) {
      expect(css(`--hive-rail-${identity}`)).toBe(d.rail[identity]);
      expect(css(`--hive-name-${identity}`)).toBe(d.name[identity]);
    }
  });

  it("no longer publishes the lightness knobs", () => {
    // Publishing them is what would let a future `oklch(from … var(--…-l) c h)`
    // slip back into the stylesheet and re-open the platform split.
    applyTheme(THEMES.pollen.dark);
    const style = document.documentElement.getAttribute("style") ?? "";
    for (const dead of [
      "--hive-turn-rail-l",
      "--hive-turn-name-l",
      "--hive-accent-ink-l",
      "--hive-fill-l",
    ]) {
      expect(style).not.toContain(dead);
    }
  });

  it("switching scheme rewrites them", () => {
    applyTheme(THEMES.pollen.light);
    const light = document.documentElement.style.getPropertyValue("--hive-danger-ink");
    applyTheme(THEMES.pollen.dark);
    expect(document.documentElement.style.getPropertyValue("--hive-danger-ink")).not.toBe(light);
  });
});

describe("the stylesheet keeps its hands off the gamut", () => {
  // Blank out comment bodies, keeping line numbers, so the guards below scan
  // declarations only — the block explaining *why* there is no oklch() in this
  // file necessarily contains the word oklch().
  const code = styleSheet.replace(/\/\*[\s\S]*?\*\//g, (m: string) => m.replace(/[^\n]/g, " "));

  it("is actually reading the stylesheet", () => {
    // Every other guard in this block is a `not.toContain`, which an empty
    // string passes. Pin the input first so a broken read fails here instead of
    // quietly turning the rest of the file green.
    expect(code).toContain("--hive-canvas");
    expect(code.length).toBeGreaterThan(1000);
  });

  it("contains no oklch()", () => {
    // The enforcement half of this change. A single `oklch(from …)` anywhere in
    // the sheet reintroduces the engine — and therefore the platform split —
    // for whichever token it builds. Derive it in lib/theme.ts instead.
    const offenders = code
      .split("\n")
      .map((line, i) => ({ line: line.trim(), n: i + 1 }))
      .filter((l) => /\boklch\(/.test(l.line))
      .map((l) => `styles.css:${l.n}: ${l.line}`);
    expect(offenders).toEqual([]);
  });

  it("does not reference the removed lightness knobs", () => {
    for (const dead of [
      "--hive-turn-rail-l",
      "--hive-turn-name-l",
      "--hive-accent-ink-l",
      "--hive-fill-l",
    ]) {
      expect(code).not.toContain(dead);
    }
  });

  it("still defines a first-paint default for every token applyTheme sets", () => {
    // :root's literals cover the gap before the theme JS runs. A token set by
    // applyTheme() but absent here paints as nothing on first frame.
    for (const token of [
      "--hive-success-ink",
      "--hive-danger-ink",
      "--hive-warn-ink",
      "--hive-warm-ink",
      "--hive-accent-fill",
      "--hive-warm-fill",
      "--hive-rail-warm",
      "--hive-name-warm",
      "--hive-rail-cool",
      "--hive-name-cool",
      "--hive-rail-muted",
      "--hive-name-muted",
    ]) {
      expect(code, `${token} has no first-paint default`).toMatch(
        new RegExp(`${token}:\\s*rgb\\(`),
      );
    }
  });

  it("the first-paint literals are the pollen-light values", () => {
    // Hand-typed literals drift. Recompute them and compare.
    const d = deriveTokens(THEMES.pollen.light);
    const declared = (token: string) =>
      code.match(new RegExp(`${token}:\\s*([^;]+);`))?.[1].trim();
    expect(declared("--hive-danger-ink")).toBe(d.dangerInk);
    expect(declared("--hive-success-ink")).toBe(d.successInk);
    expect(declared("--hive-warn-ink")).toBe(d.warnInk);
    expect(declared("--hive-warm-ink")).toBe(d.warmInk);
    expect(declared("--hive-accent-fill")).toBe(d.accentFill);
    expect(declared("--hive-warm-fill")).toBe(d.warmFill);
    expect(declared("--hive-rail-warm")).toBe(d.rail.warm);
    expect(declared("--hive-name-warm")).toBe(d.name.warm);
    expect(declared("--hive-rail-cool")).toBe(d.rail.cool);
    expect(declared("--hive-name-cool")).toBe(d.name.cool);
    expect(declared("--hive-rail-muted")).toBe(d.rail.muted);
    expect(declared("--hive-name-muted")).toBe(d.name.muted);
  });

  it("every .tt identity overrides both --tr and --tn", () => {
    // --turn-accent no longer drags the rail and name along with it, so any
    // rule that sets the accent has to set all three or it will show one
    // identity's fill against another's rail.
    const rules = code.match(/^\.tt(\.\w+)?\s*\{[^}]*\}/gm) ?? [];
    const accentRules = rules.filter((r) => /--turn-accent:/.test(r));
    expect(accentRules.length).toBeGreaterThan(0);
    for (const rule of accentRules) {
      expect(rule, `${rule.slice(0, 40)}… sets --turn-accent without --tr`).toMatch(/--tr:/);
      expect(rule, `${rule.slice(0, 40)}… sets --turn-accent without --tn`).toMatch(/--tn:/);
    }
  });
});
