// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Backend build/version info — the Phase 0 smoke-test round-trip.
 */
export type AppInfo = { name: string, coreVersion: string, buildProfile: string, };
