// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One vote on a proposal.
 */
export type ApprovalDto = { actorId: string, 
/**
 * Human-readable name of the voter, resolved from the workspace roster at
 * projection time so the Review pane can tag who approved/rejected without a
 * separate roster lookup. Falls back to a short actor id when unknown.
 */
displayName: string, role: string, approved: boolean, };
