// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One vote on a proposal.
 */
export type ApprovalDto = { actorId: string, role: string, approved: boolean, };
