// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * App + workspace settings surfaced to the Settings pane.
 */
export type AppSettingsDto = { displayName: string, 
/**
 * Git email used to attribute commits agents make on this user's behalf.
 */
gitEmail: string, deviceName: string, workspaceRoot: string, knownWorkspaces: Array<string>, model: string, gitBranch: string | null, gitDirtyCount: number, };
