// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A workspace channel — organization only, no config (spec §11).
 */
export type ChannelDto = { id: string, name: string, purpose: string | null, position: number, archived: boolean, 
/**
 * The channel's drop-in default chat (created with it).
 */
defaultChatId: string, };
