// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ephemeral background-activity for a running subprocess-agent turn (Claude
 * Code today): the tool calls it makes, their results, and a thinking marker.
 * Pushed live and NOT persisted — the UI shows it under the generating bubble
 * while the turn runs, then it's dropped when the turn completes. `kind` is
 * "tool" (a tool call — `id`/`name`/`inputJson`), "result" (its output — `id`
 * is the matching call id, `content`/`isError`), or "thinking".
 */
export type ChatActivityEvent = { sessionId: string, messageId: string, kind: string, id: string, name: string, inputJson: string, content: string, isError: boolean, };
