// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A chat as listed in the sidebar.
 */
export type ChatSummaryDto = { id: string, title: string, lastActivityAt: string, messageCount: number, archived: boolean, };
