// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A chat as listed in the sidebar.
 */
export type ChatSummaryDto = { id: string, title: string, lastActivityAt: string, messageCount: number, archived: boolean, 
/**
 * The channel this chat is filed under (empty = unfiled). Spec §11.
 */
channelId: string, 
/**
 * True when this chat is its channel's drop-in default — not movable,
 * renamable, or deletable on its own.
 */
isChannelDefault: boolean, };
