// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatMessageDto } from "./ChatMessageDto";

/**
 * A chat opened in the transcript pane.
 */
export type ChatSessionDto = { id: string, title: string, runtimeId: string, messages: Array<ChatMessageDto>, };
