// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A streaming update pushed as a Tauri event while an assistant reply is
 * generated. `phase` is "delta" (append `text`), "completed" (final body in
 * `text`), or "error" (`text` is the message).
 */
export type ChatStreamEvent = { sessionId: string, messageId: string, phase: string, text: string, };
