// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReactionDto } from "./ReactionDto";
import type { ToolCallDto } from "./ToolCallDto";
import type { ToolResultDto } from "./ToolResultDto";

/**
 * One transcript message, flattened for rendering.
 */
export type ChatMessageDto = { id: string, 
/**
 * "system" | "user" | "assistant" | "agent"
 */
role: string, author: string, body: string, isStreaming: boolean, 
/**
 * RFC 3339 timestamp.
 */
createdAt: string, reactions: Array<ReactionDto>, 
/**
 * Tool calls this assistant turn made (for inline tool-call cards).
 */
toolCalls: Array<ToolCallDto>, 
/**
 * Tool results carried by this (user-role) turn, keyed back to a call id.
 */
toolResults: Array<ToolResultDto>, 
/**
 * The author's avatar image (`data:` URL) for this turn — from the stamped
 * actor identity (humans) or the agent roster (agents). None = initials.
 */
authorAvatarUrl: string | null, 
/**
 * The author's avatar accent color (`#rrggbb`), when set. None = derived.
 */
authorColorHex: string | null, 
/**
 * For a primary-`@hive` turn: the display name of the user whose device
 * answered (every user's default agent is named "hive", so this
 * disambiguates "Alice's hive" from "Bob's hive"). None for human turns and
 * named agents (whose own name is the label).
 */
responderName: string | null, };
