// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Actual context-budget telemetry computed by the backend planner.
 */
export type ContextTelemetryDto = { sessionId: string, runtimeId: string, model: string, contextWindowTokens: number, reservedOutputTokens: number, summaryReserveTokens: number, systemPromptTokens: number, historyBudgetTokens: number, historyTokens: number, messageCount: number, keptMessageCount: number, keptTokens: number, overflowMessageCount: number, overflowTokens: number, skillCount: number, skillTokens: number, vaultCount: number, 
/**
 * "none" | "cached" | "incremental" | "fresh"
 */
summaryStrategy: string, };
