// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry in a workspace directory listing (the lazy file tree). `path` is
 * repo-relative (POSIX `/` separators, so the key is stable across platforms).
 */
export type FsEntryDto = { name: string, path: string, isDir: boolean, };
