// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One file's uncommitted change, for the Diff canvas.
 */
export type GitFileDiffDto = { path: string, 
/**
 * "modified" | "added" | "deleted" | "renamed" | "untracked" | "conflicted"
 */
kind: string, 
/**
 * Unified-diff text (synthesized for untracked files).
 */
patch: string, addedLines: number, removedLines: number, };
