// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A freshly issued token: the `raw` value is shown ONCE, never retrievable again.
 */
export type IssuedRelayTokenDto = { userId: string, userName: string, raw: string, };
