// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry in the LSP language-server registry, surfaced to the editor so it
 * can attach language intelligence only for servers the user actually has.
 */
export type LspServerDto = { 
/**
 * Stable registry id (e.g. "typescript", "rust-analyzer", "pyright", "gopls").
 */
id: string, 
/**
 * Human-readable language(s) the server serves (e.g. "typescript/javascript").
 */
language: string, 
/**
 * The command line the backend would spawn (binary + args), for display.
 */
command: string, 
/**
 * Whether the server's binary is resolvable on the current PATH. When false
 * the editor attaches nothing for this language and degrades silently.
 */
available: boolean, };
