// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A configured MCP server and whether it's enabled (the inert-until-enabled
 * gate: a disabled server is never launched/connected).
 */
export type McpServerDto = { id: string, 
/**
 * "stdio" | "http"
 */
transport: string, detail: string, enabled: boolean, isManaged: boolean, };
