// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the local user was last `@`-mentioned in a chat, so the sidebar can
 * highlight the channel (and chat) until it's read. Read state is per-device
 * (localStorage), so this DTO carries only the raw positions: a mention at
 * `last_mention_ordinal` is *unread* when it exceeds the read cursor the client
 * stored when it last opened the chat (≈ `message_count` at that time).
 */
export type MentionStateDto = { sessionId: string, 
/**
 * The channel the chat is filed under (empty = unfiled).
 */
channelId: string, 
/**
 * 1-based position (in canonical message order) of the last message that
 * mentions the local user. Always ≥ 1 (chats with none are omitted).
 */
lastMentionOrdinal: number, 
/**
 * Total messages in the chat — the value the client stores as its read
 * cursor when it opens the chat.
 */
messageCount: number, };
