// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalDto } from "./ApprovalDto";

/**
 * A proposal in the review queue, with computed quorum state.
 */
export type ProposalDto = { id: string, title: string, body: string, 
/**
 * "fileDiff" | "command" | "decision"
 */
kind: string, 
/**
 * "open" | "approved" | "rejected" | "applied"
 */
status: string, requiredApprovals: number, qualifyingApprovals: number, quorumMet: boolean, approvals: Array<ApprovalDto>, };
