// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalDto } from "./ApprovalDto";

/**
 * A proposal in the review queue, with computed quorum state.
 */
export type ProposalDto = { id: string, title: string, body: string, 
/**
 * Actor who created the proposal; their own approval doesn't count toward
 * quorum. Empty for authorless proposals (e.g. workflow gates).
 */
authorActorId: string, 
/**
 * "fileDiff" | "command" | "decision"
 */
kind: string, 
/**
 * "open" | "approved" | "rejected" | "applied"
 */
status: string, requiredApprovals: number, qualifyingApprovals: number, quorumMet: boolean, approvals: Array<ApprovalDto>, 
/**
 * For a fileDiff proposal: the unified diff the agent produced in its
 * isolated worktree (rendered in the Diff canvas; applied on Implement).
 * None for command/decision proposals.
 */
diff?: string | null, 
/**
 * Paths the diff touches, for a compact summary in the Review pane.
 */
changedFiles?: Array<string>, };
