// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One unit of queued work: an unanswered agent mention, tagged with the host
 * its agent is bound to and that host's live status. Surfaces the CLI's `hive
 * queue` in the desktop Review pane so offline/detached work is visible and
 * reassignable (spec §12.5).
 */
export type QueuedWorkDto = { sessionId: string, chatTitle: string, agentId: string, agentName: string, 
/**
 * The host the agent is bound to (empty = the owner's device).
 */
hostId: string, hostLabel: string, 
/**
 * "online" (host heartbeating) | "offline" (bound to a stale host) |
 * "device" (owner-device, no worker host) | "unknown" (host not found).
 */
hostStatus: string, };
