// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One emoji reaction on a message.
 */
export type ReactionDto = { emoji: string, actorId: string, actorDisplayName: string, };
