// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One note on a proposal's refinement thread.
 */
export type RefinementDto = { id: string, actorId: string, 
/**
 * Voter/commenter name resolved from the roster at projection time.
 */
displayName: string, role: string, text: string, requestChanges: boolean, createdAt: string, };
