// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RelayTokenDto } from "./RelayTokenDto";

/**
 * A relay access user + their tokens, for the Team management panel.
 */
export type RelayUserDto = { id: string, name: string, login: string, disabled: boolean, tokens: Array<RelayTokenDto>, };
