// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One issued relay access token's metadata (never the raw value/hash).
 */
export type RelayTokenDto = { id: string, label: string, 
/**
 * RFC-3339 or empty; "" when never used.
 */
lastUsed: string, revoked: boolean, };
