// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A configured runtime surfaced to the desktop shell.
 */
export type RuntimeSummaryDto = { id: string, name: string, label: string, provider: string, location: string, model: string, endpoint: string, supportsTools: boolean, supportsEmbeddings: boolean, isDefault: boolean, isManaged: boolean, };
