// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A loaded skill (instruction bundle injected into prompts).
 */
export type SkillDto = { id: string, name: string, instructions: string, sourceUrl: string | null, };
