// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A tool invocation an assistant turn made (MCP or built-in).
 */
export type ToolCallDto = { id: string, name: string, 
/**
 * JSON-encoded arguments.
 */
inputJson: string, serverId: string | null, };
