// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The result of a tool call, keyed to its `call_id`.
 */
export type ToolResultDto = { callId: string, content: string, isError: boolean, };
