// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A reference-material vault source mounted in the workspace.
 */
export type VaultSourceDto = { 
/**
 * "github" | "gitlab" | "https"
 */
kind: string, label: string, url: string, };
