// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One selectable workspace in the switcher: the local "My workspace", or a
 * joined relay room. The chat list is scoped to whichever is `active`.
 */
export type WorkspaceInfoDto = { id: string, name: string, 
/**
 * "local" | "room"
 */
kind: string, active: boolean, 
/**
 * Optional workspace icon as a `data:` URL (set by an owner/admin); when
 * present the rail renders it in place of the initials/brand mark.
 */
iconUrl: string | null, };
