// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowNodeDto } from "./WorkflowNodeDto";

/**
 * A workflow definition (DAG of stages) available in a chat.
 */
export type WorkflowDefinitionDto = { id: string, name: string, description: string, inputLabel: string | null, nodes: Array<WorkflowNodeDto>, };
