// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Live state of one stage within a run.
 */
export type WorkflowNodeRunDto = { nodeId: string, name: string, 
/**
 * "agent" | "gate"
 */
kind: string, 
/**
 * "pending" | "running" | "awaitingApproval" | "succeeded" | "failed" |
 * "rejected" | "skipped"
 */
status: string, messageId: string | null, proposalId: string | null, outputExcerpt: string, attempts: number, error: string, };
