// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A workspace member with a governance role.
 */
export type WorkspaceMemberDto = { id: string, 
/**
 * The member's actor id — used to match against the presence feed (online).
 */
actorId: string, displayName: string, 
/**
 * "owner" | "admin" | "contributor" | "viewer"
 */
role: string, title: string, 
/**
 * Per-workspace join index (1-based). Disambiguates duplicate display
 * names — surfaced as `Name #N`, matchable as `@Name#N`.
 */
index: number, 
/**
 * True when this member is the local user. The People list hides "you"
 * (you're shown in the identity card), so it shows only collaborators.
 */
isSelf: boolean, };
