// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A registered workspace host, for the "run on worker" reassignment menu.
 */
export type WorkspaceHostDto = { id: string, 
/**
 * "device" | "worker"
 */
kind: string, label: string, online: boolean, };
