// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One stage of a workflow definition, flattened for the wire: `kind` is
 * "agent" | "gate" and only that kind's optionals are populated.
 */
export type WorkflowNodeDto = { id: string, name: string, dependsOn: Array<string>, 
/**
 * "agent" | "gate"
 */
kind: string, 
/**
 * Agent stages: workspace agent id, empty ⇒ session primary runtime.
 */
agentId: string | null, promptTemplate: string | null, 
/**
 * Gate stages.
 */
gateTitle: string | null, gateBody: string | null, requiredApprovals: number | null, 
/**
 * "halt" | "routeTo"
 */
onReject: string | null, rejectTarget: string | null, 
/**
 * Builder-canvas position (px); null ⇒ auto-layout.
 */
x: number | null, y: number | null, };
