// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Pushed as a Tauri event whenever a run's persisted state changes.
 */
export type WorkflowRunEvent = { sessionId: string, runId: string, status: string, };
