// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowNodeRunDto } from "./WorkflowNodeRunDto";

/**
 * A workflow run card: frozen definition name + per-stage state.
 */
export type WorkflowRunDto = { id: string, definitionId: string, definitionName: string, input: string, 
/**
 * "running" | "awaitingGate" | "completed" | "failed" | "halted" | "canceled"
 */
status: string, nodes: Array<WorkflowNodeRunDto>, startedAt: string, 
/**
 * Whether an in-process driver is live for this run right now. False after
 * an app restart until crash-recovery re-spawns the driver; gates the
 * frontend's Resume affordance.
 */
driverAlive: boolean, };
