// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A workspace agent in the roster (a named participant on a runtime).
 */
export type WorkspaceAgentDto = { id: string, name: string, runtimeId: string, role: string, };
