// Ground-truth extractor for the derived colour layer.
//
// The derived tokens are built in CSS on the desktop. Porting them to JS is the
// one part of this app that can be wrong *quietly* — a bad OKLCH conversion
// does not throw, it just renders a slightly different colour that nobody
// catches without a side-by-side. So the fixture the unit tests assert against
// is neither hand-written nor generated by our own implementation: it is
// measured out of a real browser, the same engine the desktop shell renders in.
//
//   bun run tools/extract-desktop-tokens.ts
//
// Writes src/theme/__tests__/fixtures/derived-tokens.json.
//
// Two measurement methods, because neither one alone is sound:
//
//  * sRGB `color-mix()` tokens are read from `getComputedStyle`. They are
//    in-gamut and often translucent, and computed style reports them exactly.
//    Screenshotting them instead would be actively wrong: a 6% hover tint
//    composited over a backdrop and then un-composited amplifies the 8-bit
//    rounding error by 1/alpha — about 17x — so a perfectly correct
//    implementation would appear to be off by 8 counts.
//
//  * `oklch()` tokens are read from *rendered pixels*, via a screenshot.
//    Computed style is useless here: it serialises an out-of-gamut `oklch()`
//    straight back as `oklch()`, telling you what you asked for rather than
//    what the user sees. The whole question is what the engine does when the
//    colour does not fit in sRGB, and only the pixels answer it.

import { mkdirSync, writeFileSync, rmSync, existsSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { tmpdir } from "node:os";
import { basename, join } from "node:path";
import { CHAT, STATUS, THEMES, THEME_NAMES } from "../src/theme/palettes";

const CHROMIUM_CANDIDATES = [
  "C:/Program Files/Google/Chrome/Application/chrome.exe",
  "C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe",
  "/usr/bin/google-chrome",
  "/usr/bin/chromium",
  "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
];

interface Swatch {
  /// `<theme>.<scheme>.<token>`
  key: string;
  /// The CSS the desktop stylesheet would evaluate for this token.
  css: string;
}

/// Every colour the CSS layer derives, spelled exactly as the stylesheet
/// spells it, so the browser does the deriving and we only read the result.
function collect(): { mixes: Swatch[]; oklchs: Swatch[] } {
  const mixes: Swatch[] = [];
  const oklchs: Swatch[] = [];

  for (const name of THEME_NAMES) {
    for (const scheme of ["light", "dark"] as const) {
      const p = THEMES[name][scheme];
      const s = STATUS[scheme];
      const c = CHAT[scheme];
      const prefix = `${name}.${scheme}`;
      const mix = (token: string, css: string) => mixes.push({ key: `${prefix}.${token}`, css });
      const lch = (token: string, src: string, l: number) =>
        oklchs.push({ key: `${prefix}.${token}`, css: `oklch(from ${src} ${l} c h)` });

      // --- :root sRGB derivations ---
      mix("inkSoft", `color-mix(in srgb, ${p.ink} 55%, transparent)`);
      mix("inkFaint", `color-mix(in srgb, ${p.ink} 42%, transparent)`);
      mix("hover", `color-mix(in srgb, ${p.ink} 6%, transparent)`);
      mix("tintCool", `color-mix(in srgb, ${p.accentCool} 14%, transparent)`);
      mix("tintCoolLine", `color-mix(in srgb, ${p.accentCool} 38%, transparent)`);
      mix("tintWarm", `color-mix(in srgb, ${p.accentWarm} 13%, transparent)`);
      mix("tintWarmLine", `color-mix(in srgb, ${p.accentWarm} 40%, transparent)`);
      const muted = `color-mix(in srgb, ${p.ink} 34%, ${p.panel})`;
      mix("accentMuted", muted);

      // --- .tt turn fills ---
      mix("human.fill", `color-mix(in srgb, ${p.panel} 92%, ${p.accentWarm})`);
      mix("agent.fill", `color-mix(in srgb, ${p.panel} 92%, ${p.accentCool})`);
      mix("human.fillPressed", `color-mix(in srgb, ${p.panel} 88%, ${p.accentWarm})`);
      mix("agent.fillPressed", `color-mix(in srgb, ${p.panel} 88%, ${p.accentCool})`);
      mix("shared.fillPressed", `color-mix(in srgb, ${p.mist} 90%, ${p.ink})`);

      // --- :root OKLCH derivations ---
      lch("successInk", s.success, c.accentInkL);
      lch("dangerInk", s.danger, c.accentInkL);
      lch("warnInk", s.warn, c.accentInkL);
      lch("warmInk", p.accentWarm, c.accentInkL);
      lch("accentFill", p.accentCool, c.fillL);
      lch("warmFill", p.accentWarm, c.fillL);

      // --- per-turn rail (--tr) and tinted handle (--tn) ---
      for (const [kind, accent] of [
        ["human", p.accentWarm],
        ["agent", p.accentCool],
        ["shared", muted],
      ] as const) {
        lch(`${kind}.rail`, accent, c.turnRailL);
        lch(`${kind}.tag`, accent, c.turnNameL);
      }
    }
  }
  return { mixes, oklchs };
}

function findChromium(): string {
  const fromEnv = process.env.CHROMIUM_BIN;
  if (fromEnv && existsSync(fromEnv)) return fromEnv;
  for (const c of CHROMIUM_CANDIDATES) if (existsSync(c)) return c;
  throw new Error("no Chromium found — set CHROMIUM_BIN to a Chrome/Edge binary and re-run");
}

/// A private profile dir, so the run cannot be hijacked by an already-open
/// browser session (which silently turns headless flags into a no-op).
function runChromium(bin: string, args: string[], profile: string) {
  return spawnSync(
    bin,
    ["--headless", "--disable-gpu", "--no-first-run", `--user-data-dir=${profile}`, ...args],
    { encoding: "utf8", maxBuffer: 64 * 1024 * 1024 },
  );
}

/// The renderer's version string, recorded in the fixture so a future reader
/// knows which engine measured it.
///
/// This must not start a browser, and on Windows that rules out `--version`.
/// `--version` is a POSIX-only switch: on Windows Chrome does not recognise it,
/// ignores it, and starts a *normal* browser — and with no `--user-data-dir`
/// that browser opens on the user's own profile. `spawnSync`'s `timeout` then
/// kills it. To the person at the keyboard that is Hive killing their browser
/// and restarting it, some seconds after they ran a test command. It also
/// silently produced an empty version string, which is why the committed
/// fixture recorded a bare binary path where a version belongs.
///
/// The PE version resource carries the same string and starts no process.
function chromiumVersion(bin: string): string {
  if (process.platform === "win32") {
    const r = spawnSync(
      "powershell",
      ["-NoProfile", "-Command", `(Get-Item ${JSON.stringify(bin)}).VersionInfo.ProductVersion`],
      { encoding: "utf8", timeout: 15_000 },
    );
    const v = r.stdout?.trim();
    return v ? `${basename(bin)} ${v}` : bin;
  }
  // Elsewhere `--version` genuinely prints and exits without opening a window.
  return spawnSync(bin, ["--version"], { encoding: "utf8", timeout: 15_000 }).stdout.trim() || bin;
}

/// Normalise whatever the engine hands back — `rgb()`, `rgba()`, or the
/// `color(srgb …)` form modern Chromium uses for `color-mix` results.
function normalise(serialised: string): string {
  const c4 = serialised.match(/^color\(srgb\s+([^)]+)\)$/);
  if (c4) {
    const parts = c4[1].replace("/", " ").split(/\s+/).filter(Boolean).map(Number);
    const [r, g, b] = parts.slice(0, 3).map((v) => Math.round(v * 255));
    const a = parts.length > 3 ? parts[3] : 1;
    return a >= 1 ? `rgb(${r}, ${g}, ${b})` : `rgba(${r}, ${g}, ${b}, ${Math.round(a * 1000) / 1000})`;
  }
  const fn = serialised.match(/^rgba?\(([^)]*)\)$/);
  if (!fn) throw new Error(`unexpected computed colour: ${serialised}`);
  const n = fn[1].replace(/\//g, " ").split(/[\s,]+/).filter(Boolean).map(Number);
  const a = n.length > 3 ? n[3] : 1;
  return a >= 1
    ? `rgb(${n[0]}, ${n[1]}, ${n[2]})`
    : `rgba(${n[0]}, ${n[1]}, ${n[2]}, ${Math.round(a * 1000) / 1000})`;
}

/// Read in-gamut sRGB mixes out of `getComputedStyle`, exactly.
function measureComputed(bin: string, dir: string, profile: string, list: Swatch[]) {
  const data = JSON.stringify(list.map((s) => s.css));
  const html = `<!doctype html><meta charset="utf-8"><div id="probe"></div><pre id="out"></pre>
<script>
const css = ${data};
const probe = document.getElementById("probe");
const lines = css.map((c) => {
  probe.style.color = "";
  probe.style.color = c;
  return getComputedStyle(probe).color;
});
document.getElementById("out").textContent = "@@" + JSON.stringify(lines) + "@@";
</script>`;
  const file = join(dir, "computed.html");
  writeFileSync(file, html, "utf8");
  const r = runChromium(bin, ["--dump-dom", `file:///${file.replace(/\\/g, "/")}`], profile);
  const m = r.stdout.match(/@@(\[.*?\])@@/s);
  if (!m) throw new Error(`computed-style probe produced no output:\n${r.stdout.slice(0, 500)}`);
  const values: string[] = JSON.parse(m[1]);
  if (values.length !== list.length) throw new Error("computed-style probe returned wrong count");
  return values.map(normalise);
}

// A swatch is a flat CELL x CELL block; we sample its centre so that any
// rasteriser edge antialiasing cannot contaminate the reading.
const CELL = 10;
const COLS = 40;

/// Read out-of-gamut OKLCH colours out of rendered pixels.
function measureRendered(bin: string, dir: string, profile: string, list: Swatch[]) {
  const divs = list
    .map((s, i) => {
      const x = (i % COLS) * CELL;
      const y = Math.floor(i / COLS) * CELL;
      return `<i style="left:${x}px;top:${y}px;background:${s.css}"></i>`;
    })
    .join("");
  const html = `<!doctype html><html><head><meta charset="utf-8"><style>
html,body{margin:0;padding:0;background:#000}
i{position:absolute;display:block;width:${CELL}px;height:${CELL}px}
</style></head><body>${divs}</body></html>`;
  const file = join(dir, "swatches.html");
  const png = join(dir, "swatches.png");
  writeFileSync(file, html, "utf8");

  const rows = Math.ceil(list.length / COLS);
  const r = runChromium(
    bin,
    [
      // Without this the screenshot can land in the display profile rather than
      // sRGB, shifting every reading by a few counts.
      "--force-color-profile=srgb",
      `--screenshot=${png}`,
      `--window-size=${COLS * CELL},${rows * CELL}`,
      "--virtual-time-budget=4000",
      `file:///${file.replace(/\\/g, "/")}`,
    ],
    profile,
  );
  if (!existsSync(png)) throw new Error(`screenshot failed: ${r.stderr.slice(0, 500)}`);

  const points = list.map((_, i) => [
    (i % COLS) * CELL + Math.floor(CELL / 2),
    Math.floor(i / COLS) * CELL + Math.floor(CELL / 2),
  ]);
  return readPixels(png, points).map(([r8, g8, b8]) => `rgb(${r8}, ${g8}, ${b8})`);
}

/// Neither Node nor Bun ships an image decoder, so this shells out: PowerShell
/// + System.Drawing on Windows, ImageMagick elsewhere.
function readPixels(png: string, points: number[][]): Array<[number, number, number]> {
  if (process.platform === "win32") {
    const script = `
Add-Type -AssemblyName System.Drawing
$b = [System.Drawing.Bitmap]::FromFile('${png.replace(/\//g, "\\")}')
$pts = @(${points.map(([x, y]) => `@(${x},${y})`).join(",")})
$out = foreach ($p in $pts) { $c = $b.GetPixel($p[0], $p[1]); "$($c.R),$($c.G),$($c.B)" }
$b.Dispose()
$out -join ';'
`;
    const r = spawnSync("powershell", ["-NoProfile", "-Command", script], {
      encoding: "utf8",
      maxBuffer: 64 * 1024 * 1024,
    });
    if (r.status !== 0) throw new Error(`pixel read failed: ${r.stderr}`);
    return r.stdout
      .trim()
      .split(";")
      .map((t) => t.trim().split(",").map(Number) as [number, number, number]);
  }

  const r = spawnSync(
    "magick",
    [png, "-format", points.map(([x, y]) => `%[pixel:p{${x},${y}}]`).join(";"), "info:"],
    { encoding: "utf8" },
  );
  if (r.status !== 0) throw new Error("pixel read needs ImageMagick (`magick`) on this platform");
  return r.stdout
    .trim()
    .split(";")
    .map((t) => {
      const m = t.match(/(\d+),(\d+),(\d+)/);
      if (!m) throw new Error(`unreadable pixel: ${t}`);
      return [Number(m[1]), Number(m[2]), Number(m[3])] as [number, number, number];
    });
}

function main() {
  const { mixes, oklchs } = collect();
  const dir = join(tmpdir(), "hive-token-extract");
  const profile = join(dir, "profile");
  rmSync(dir, { recursive: true, force: true });
  mkdirSync(profile, { recursive: true });

  const bin = findChromium();
  const version = chromiumVersion(bin);

  const tokens: Record<string, string> = {};
  const computed = measureComputed(bin, dir, profile, mixes);
  mixes.forEach((s, i) => (tokens[s.key] = computed[i]));
  const rendered = measureRendered(bin, dir, profile, oklchs);
  oklchs.forEach((s, i) => (tokens[s.key] = rendered[i]));

  const fixture = {
    _comment:
      "Measured from a real browser — do not hand-edit. sRGB mixes via " +
      "getComputedStyle (exact); oklch() via rendered pixels (the only way to " +
      "see what the engine does out of gamut). Regenerate with " +
      "`bun run tools/extract-desktop-tokens.ts`.",
    _renderer: version,
    tokens,
  };

  const dest = join(import.meta.dir, "..", "src", "theme", "__tests__", "fixtures");
  mkdirSync(dest, { recursive: true });
  writeFileSync(
    join(dest, "derived-tokens.json"),
    JSON.stringify(fixture, null, 2) + "\n",
    "utf8",
  );
  rmSync(dir, { recursive: true, force: true });
  console.log(
    `wrote ${Object.keys(tokens).length} measured tokens ` +
      `(${mixes.length} computed, ${oklchs.length} rendered) from ${version}`,
  );
}

main();
